name: on-push-branch

on:
  push:
    branches:
      - 'master'
      - 'feature-*'
      - 'hotfix-*'
      - 'bug-*'

jobs:
  unit-test:
    name: api test - run unitest on action
    runs-on: ubuntu-latest
    container: golang:1.16
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testing
          POSTGRES_PASSWORD: testing
          POSTGRES_PORT: 5432
          POSTGRES_USER: sewakantor
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        go: [ '1.16' ]
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v2
      - name: running unitest
        env:
          DB_USER: sewakantor
          DB_HOST: postgres
          DB_PORT: 5432
          DB_PASS: testing
          DB_NAME: testing
        run: |
          go mod tidy
          go test ./... -cover -failfast